window.DEBRIEF_CONTENT = {
  edition: {
    isoDate: "2026-07-31",
    dateLabel: "Friday, July 31, 2026",
    shortDate: "Fri, Jul 31",
    generatedLabel: "Generated Friday, July 31, 2026 at 9:15 AM ET",
    cotDate: "Tuesday, July 21, 2026",
    readTime: "16 min briefing",
  },

  leadId: "amazon-aws-apple-eci",

  stories: [
    {
      id: "amazon-aws-apple-eci",
      page: "markets",
      category: "Earnings, Rates & AI",
      source: "Amazon + Apple + BLS + AP",
      sourceUrl: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
      updated: "9:15 AM ET",
      readTime: "8 min read",
      headline: "AWS clears the AI revenue test as Apple meets a quality discount",
      deck: "Amazon paired 37% AWS growth with a much larger infrastructure bill, while Apple's record quarter included a material tariff-refund benefit. Friday's 0.9% Employment Cost Index increase keeps the 10-year yield near 4.70% and raises the cash-return bar for both.",
      summary: "Amazon reported $200.6 billion of sales and 37% AWS growth, but trailing free cash flow fell to negative $7.6 billion as property spending reached $169.0 billion. Apple delivered $109.4 billion of revenue and $2.02 of EPS; management said tariff refunds added about two points to gross margin and $0.11 to EPS.",
      tags: ["Amazon", "Apple", "ECI", "AI returns"],
      numbers: [
        { label: "AWS growth", value: "+37%", change: "$42.2B revenue", tone: "up" },
        { label: "Apple revenue", value: "$109.4B", change: "+16% YoY", tone: "up" },
        { label: "ECI", value: "+0.9%", change: "Q/Q", tone: "down" },
        { label: "U.S. 10Y", value: "4.70%", change: "9:02 AM ET", tone: "down" },
      ],
      sections: [
        {
          id: "amazon",
          title: "AWS converted capacity into operating leverage",
          paragraphs: [
            "Amazon's second-quarter sales rose 20% to $200.61 billion and operating income increased 43% to $27.46 billion. AWS revenue accelerated 37% to $42.23 billion, its fastest growth in 18 quarters, while AWS operating income reached $16.62 billion for a 39.4% margin.",
            "The result answers the first AI-return question: installed capacity is finding demand. Amazon said its AWS AI business and custom-chip business each exceed a $25 billion annual revenue run rate. The next question is whether that demand can outrun the cash cost of building ahead of it.",
          ],
        },
        {
          id: "cash",
          title: "The cash-flow bill is the counterweight",
          paragraphs: [
            "Amazon's $62.65 billion of net income included $53.4 billion of pre-tax non-operating income, primarily from its Anthropic investment. Operating income and cash flow therefore describe the recurring quarter better than headline EPS.",
            "Trailing property and equipment purchases rose 64% to $169.01 billion and trailing free cash flow moved to negative $7.60 billion from positive $18.18 billion. AP reported management now expects roughly $220 billion of 2026 capital spending. AWS growth is exceptional, but the valuation still depends on utilization, depreciation and power economics.",
          ],
          pullQuote: "The AI build is producing revenue; Friday's debate is how much durable cash each dollar of capacity can earn.",
        },
        {
          id: "apple",
          title: "Apple's record quarter came with an earnings-quality footnote",
          paragraphs: [
            "Apple's fiscal third-quarter revenue rose 16% to $109.42 billion and diluted EPS increased 29% to $2.02. iPhone revenue reached $54.25 billion, Services $30.74 billion and Greater China $18.82 billion, all well above the prior-year comparisons except iPad, which declined.",
            "The quality adjustment matters. Apple said favorable tariff refunds added about two percentage points to its 50.1% gross margin and $0.11 to EPS. Quarterly R&D also climbed to $11.73 billion. Axios reported the shares down about 4% after hours despite the headline beat, a reminder that exceptional results can still miss an elevated valuation bar.",
          ],
        },
        {
          id: "friday",
          title: "Friday morning keeps duration in the frame",
          paragraphs: [
            "The Employment Cost Index rose 0.9% in the second quarter and 3.4% over 12 months. Wages rose 0.9% quarter over quarter, while benefits increased 1.0%. The data did not deliver the clean labor-cost cooling that duration-sensitive equities would prefer after this week's divided Fed decision.",
            "At 9:02 a.m. ET, the delayed feed showed the 10-year yield at 4.70%, the dollar index up 0.49%, Brent at $90.22 and bitcoin at $63,696. The S&P 500, Nasdaq and Dow figures still reflect Thursday's cash close, not Friday trading: +1.66%, +2.78% and +1.19%, respectively.",
          ],
          bullets: [
            "Rates: whether the 10-year can hold near 4.70% after the ECI release.",
            "Earnings quality: operating income and cash flow versus investment marks and tariff refunds.",
            "Breadth: whether Thursday's semiconductor and Microsoft rebound survives Friday's open.",
            "Cross-asset risk: a firmer dollar and oil tape beside weaker gold and crypto.",
          ],
        },
      ],
      sources: [
        {
          label: "Amazon: second-quarter 2026 results and cash-flow tables",
          url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
        },
        {
          label: "Apple: fiscal third-quarter 2026 results",
          url: "https://www.apple.com/newsroom/2026/07/apple-reports-third-quarter-results/",
        },
        {
          label: "BLS: second-quarter Employment Cost Index",
          url: "https://www.bls.gov/news.release/eci.nr0.htm",
        },
        {
          label: "AP: Amazon results, AWS acceleration and 2026 capex",
          url: "https://apnews.com/article/b4ce02b4666a35b8975823c5c22072ee",
        },
        {
          label: "Axios: Apple beat and tariff-refund quality adjustment",
          url: "https://www.axios.com/2026/07/30/apple-earnings-beat-estimates-boosted-tariff-refunds",
        },
      ],
    },
    {
      id: "thursday-ai-rebound-close",
      page: "markets",
      category: "Market Structure",
      source: "AP + Yahoo Finance + The Debrief",
      sourceUrl: "https://apnews.com/article/stock-markets-rates-korea-ai-oil-99b5702d93a2b5c6e513fb952ccdcc92",
      updated: "Thursday close",
      readTime: "4 min read",
      headline: "Microsoft's 15.5% surge turned the chip unwind into a one-day reversal",
      deck: "Thursday repaired the cap-weighted indices and semiconductors, but rates and Friday earnings quality still decide whether the move becomes durable breadth or another concentrated AI rally.",
      summary: "The S&P 500 gained 1.66%, the Nasdaq 2.78% and the Dow 1.19%. Microsoft rose 15.5%, Micron 18.4%, Lam Research 18% and AMD 13%, while Meta fell 8% and the 10-year yield finished near 4.67%.",
      tags: ["Breadth", "Semiconductors", "Microsoft"],
      numbers: [
        { label: "S&P 500", value: "7,437.63", change: "+1.66%", tone: "up" },
        { label: "Nasdaq", value: "25,122.18", change: "+2.78%", tone: "up" },
        { label: "SOXX", value: "$504.53", change: "+8.50%", tone: "up" },
        { label: "Microsoft", value: "+15.5%", change: "best in ~18 years", tone: "up" },
      ],
      sections: [
        {
          id: "close",
          title: "The rebound was broad enough to matter",
          paragraphs: [
            "The S&P 500 closed at 7,437.63, the Nasdaq at 25,122.18 and the Dow at 52,208.06. The Russell 2000 gained 1.37%, high-yield credit rose 0.29% and SOXX jumped 8.50%, so the repair extended beyond one mega-cap stock.",
            "The semiconductor rebound was especially forceful: AP reported Micron up 18.4%, Lam Research 18% and AMD 13%. Those moves reversed Wednesday's liquidation, but they also reset expectations at a speed that makes Friday follow-through more informative than Thursday's magnitude alone.",
          ],
        },
        {
          id: "concentration",
          title: "Microsoft supplied the index engine",
          paragraphs: [
            "Microsoft's 15.5% gain was its strongest session in nearly 18 years and followed 43% Azure growth plus an 84% increase in commercial remaining performance obligation. That provided a direct bridge from AI infrastructure spending to contracted demand.",
            "Meta's 8% decline showed the opposite side of the same trade. Strong demand is not enough when cash conversion falls sharply. Thursday's close therefore rewarded measurable returns rather than applying a blanket AI multiple to every large spender.",
          ],
        },
        {
          id: "friday-test",
          title: "Friday's confirmation test",
          paragraphs: [
            "The delayed VIX quote was 17.24 at 9:02 a.m. ET Friday, but the 10-year yield had moved to 4.70% and the dollar was firmer. A durable risk-on session needs Thursday's credit and small-cap participation to survive those tighter cross-asset inputs.",
            "The strongest confirmation would be positive breadth in semiconductors, software and cyclicals after the open. A rally confined to Amazon while Apple and rate-sensitive groups weaken would preserve the index gain but reduce its informational quality.",
          ],
        },
      ],
      sources: [
        {
          label: "AP: Thursday stock rebound, rates and AI earnings",
          url: "https://apnews.com/article/stock-markets-rates-korea-ai-oil-99b5702d93a2b5c6e513fb952ccdcc92",
        },
        {
          label: "AP: major U.S. index closes for July 30",
          url: "https://apnews.com/article/wall-street-stocks-dow-nasdaq-212b44c316056c9de10f90db562f3aed",
        },
        {
          label: "Yahoo Finance: delayed S&P 500 market data",
          url: "https://finance.yahoo.com/quote/%5EGSPC/",
        },
      ],
    },
    {
      id: "alphabet-capex-reset",
      page: "technology",
      category: "Technology",
      source: "AP + Reuters",
      sourceUrl: "https://apnews.com/article/f914606d842d4c6848019083d667fc3a",
      updated: "Post-earnings",
      readTime: "5 min read",
      headline: "Alphabet's AI demand is real; so is the capex test",
      deck: "Cloud growth and advertising strength beat expectations, but a larger spending plan moved the debate from demand to returns.",
      summary: "Alphabet's revenue rose 24% to $119.8 billion and Cloud grew 82%, while management raised 2026 capital expenditure expectations to $195 billion-$205 billion. Net income reached $112.11 billion largely because of an investment gain, making operating cash flow more useful than headline EPS.",
      tags: ["Alphabet", "Cloud", "Capex"],
      numbers: [
        { label: "Q2 revenue", value: "$119.8B", change: "+24% YoY", tone: "up" },
        { label: "Cloud growth", value: "+82%", change: "$24.8B revenue", tone: "up" },
        { label: "2026 capex", value: "$195–205B", change: "raised", tone: "down" },
      ],
      sections: [
        {
          id: "result",
          title: "The result",
          paragraphs: [
            "Alphabet's quarter showed that AI demand is supporting both cloud usage and the core advertising engine. Revenue increased 24% to $119.8 billion, Google Cloud revenue grew 82% to $24.8 billion and the Gemini app reached 950 million monthly active users.",
            "Net income of $112.11 billion was boosted by roughly $98 billion of investment gains, largely linked to SpaceX. That makes operating income and cash flow better measures of repeatable business performance than the quarter's headline earnings.",
          ],
        },
        {
          id: "economics",
          title: "The economics investors are testing",
          paragraphs: [
            "AI infrastructure is front-loaded. Cash leaves before data centers fill, depreciation persists after the initial build, and returns depend on sustained demand plus pricing discipline. Strong cloud growth helps, but the bar rises every time the spending plan rises.",
            "Alphabet raised its 2026 capital-spending range to $195 billion-$205 billion. The key question is no longer whether it can fund the build; it is whether incremental AI revenue and cloud operating income can grow fast enough to preserve free cash flow and returns on invested capital.",
          ],
        },
        {
          id: "readthrough",
          title: "The read-through for the stack",
          paragraphs: [
            "Higher hyperscaler capex supports accelerators, networking, memory, power and cooling suppliers. It is less automatically positive for software and platform multiples if the same investment wave lifts depreciation and operating costs.",
          ],
          bullets: [
            "Positive: demand visibility for chips, networking and data-center infrastructure.",
            "Open question: utilization and pricing as capacity comes online.",
            "Risk: free cash flow becomes more sensitive to any slowdown in cloud growth.",
          ],
        },
      ],
      sources: [
        {
          label: "AP: Alphabet Q2 earnings and AI demand",
          url: "https://apnews.com/article/f914606d842d4c6848019083d667fc3a",
        },
        {
          label: "Reuters via Euronext: Alphabet raises capex outlook",
          url: "https://live.euronext.com/en/financial-news/google-increases-capex-forecast-again-after-cloud-driven-earnings-beat",
        },
        {
          label: "Google: Q2 2026 operating and product highlights",
          url: "https://blog.google/company-news/inside-google/message-ceo/alphabet-earnings-q2-2026/",
        },
      ],
    },
    {
      id: "eci-labor-costs-rates",
      page: "markets",
      category: "Economy & Rates",
      source: "Bureau of Labor Statistics",
      sourceUrl: "https://www.bls.gov/news.release/eci.nr0.htm",
      updated: "8:30 AM ET",
      readTime: "5 min read",
      headline: "Labor costs rise 0.9%, keeping the Fed's inflation debate active",
      deck: "Compensation growth held at a pace that is cooler than last year but not soft enough to remove the wage-and-services risk premium from Treasury yields.",
      summary: "Civilian compensation rose 0.9% in the second quarter and 3.4% over 12 months. Wages increased 3.2% year over year and benefits 3.8%; private-sector real wages were down 0.4% after adjusting for consumer prices.",
      tags: ["ECI", "Wages", "Federal Reserve"],
      numbers: [
        { label: "Total comp.", value: "+0.9%", change: "Q/Q", tone: "down" },
        { label: "Total comp.", value: "+3.4%", change: "YoY", tone: "flat" },
        { label: "Wages", value: "+3.2%", change: "YoY", tone: "flat" },
        { label: "Benefits", value: "+3.8%", change: "YoY", tone: "down" },
      ],
      sections: [
        {
          id: "headline",
          title: "The quarterly pace did not break lower",
          paragraphs: [
            "The Employment Cost Index for civilian workers rose 0.9% from March to June. Wages and salaries also increased 0.9%, while benefit costs rose 1.0%. Over 12 months, total compensation increased 3.4%, compared with 3.6% in the year through March.",
            "The annual direction is gradually cooler, but the quarterly rate is still firm. Private-sector compensation rose 3.3% year over year and state and local government compensation rose 3.6%, leaving labor costs above the Fed's comfort zone even as they decelerate.",
          ],
        },
        {
          id: "real-wages",
          title: "Nominal wage resilience is not the same as real income growth",
          paragraphs: [
            "Private-industry wages rose 3.1% over 12 months, but the BLS inflation-adjusted series showed them down 0.4%. Workers are seeing nominal gains while higher consumer prices absorb the purchasing-power improvement.",
            "For companies, the same mix creates a two-sided margin problem: labor costs remain sticky while customers have less real income growth. Businesses with pricing power and productivity gains can absorb that pressure; labor-intensive, rate-sensitive companies face a narrower path.",
          ],
        },
        {
          id: "market",
          title: "The market read-through is duration, not an immediate policy call",
          paragraphs: [
            "The ECI does not dictate the next Fed move by itself, but it reduces the chance that investors can ignore wage persistence after a 9-3 hold with three dissenters favoring a hike. The delayed 10-year yield moved to 4.70% after the release.",
            "Friday's remaining confirmation points are the Chicago PMI and revised University of Michigan sentiment. A firmer growth read with sticky labor costs would keep upward pressure on term yields; softer activity with stable credit would be a friendlier duration mix.",
          ],
          bullets: [
            "Watch the 10-year yield around 4.70% and the dollar index near 100.35.",
            "Separate nominal wage growth from inflation-adjusted purchasing power.",
            "Compare labor-intensive company guidance with measured productivity gains.",
            "Use monthly payrolls and inflation data to confirm the quarterly ECI signal.",
          ],
        },
      ],
      sources: [
        {
          label: "BLS: Employment Cost Index, June 2026",
          url: "https://www.bls.gov/news.release/eci.nr0.htm",
        },
        {
          label: "Federal Reserve: July 29 policy statement and vote",
          url: "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm",
        },
        {
          label: "Kiplinger: July 31 economic calendar",
          url: "https://www.kiplinger.com/investing/economy/this-weeks-economic-calendar",
        },
      ],
    },
    {
      id: "amd-open-ai-stack",
      page: "technology",
      category: "Semiconductors",
      source: "AMD + Investing.com",
      sourceUrl: "https://www.amd.com/en/corporate/events/advancing-ai/keynote.html",
      updated: "Post-keynote",
      readTime: "4 min read",
      headline: "AMD made the rack, software and customer proof one AI product",
      deck: "Helios, ROCm AI and named deployments move AMD's pitch from alternative accelerators toward an integrated operating system for AI infrastructure.",
      summary: "AMD used Advancing AI 2026 to frame Helios as a rack-scale system and introduced ROCm AI for AI-assisted GPU programming. The next test is commercial: repeatable deployments, software reliability and profitable capacity growth.",
      tags: ["AMD", "ROCm", "AI systems"],
      numbers: [
        { label: "Helios", value: "rack scale", change: "integrated", tone: "up" },
        { label: "ROCm AI", value: "agentic", change: "developer tools", tone: "up" },
        { label: "MI455X", value: "deployed", change: "OpenAI cited", tone: "up" },
      ],
      sections: [
        {
          id: "event",
          title: "What AMD presented",
          paragraphs: [
            "AMD put Helios at the center of a broader system story spanning accelerators, EPYC CPUs, Pensando networking and ROCm. The keynote also introduced ROCm AI, described as an agentic platform for AI-assisted GPU programming.",
            "Named deployment evidence matters more than another peak-performance claim. OpenAI said it had deployed MI455X racks before the event, while AMD's expanding customer roster gives investors a clearer way to test whether the stack is moving from evaluation into production.",
          ],
        },
        {
          id: "competition",
          title: "Where competition has moved",
          paragraphs: [
            "The competitive unit is increasingly the rack, not the chip. Power delivery, memory, interconnect, networking and software libraries decide how much useful compute a customer gets from a capital budget.",
            "AMD can win without matching every part of a rival ecosystem, but it must show that Helios is easy to deploy at scale and that ROCm reduces, rather than relocates, engineering cost. Customer concentration and supply execution remain the next financial tests.",
          ],
        },
        {
          id: "signals",
          title: "Signals worth carrying forward",
          bullets: [
            "Named customers moving from initial racks to repeat orders.",
            "ROCm AI adoption and measurable developer productivity.",
            "Rack-level availability, power efficiency and service quality.",
            "Gross-margin evidence that supply can support a broader commercial ramp.",
          ],
        },
      ],
      sources: [
        {
          label: "AMD: Advancing AI 2026 keynote",
          url: "https://www.amd.com/en/corporate/events/advancing-ai/keynote.html",
        },
        {
          label: "Investing.com: AMD keynote transcript and takeaways",
          url: "https://uk.investing.com/news/transcripts/amd-at-advancing-ai-2026-keynote-a-bigger-bet-on-scale-93CH-4786143",
        },
      ],
    },
    {
      id: "apple-q3-quality",
      page: "technology",
      category: "Hardware & Services",
      source: "Apple + Axios",
      sourceUrl: "https://www.apple.com/newsroom/2026/07/apple-reports-third-quarter-results/",
      updated: "Post-earnings",
      readTime: "5 min read",
      headline: "Apple's record quarter needs a tariff-adjusted quality read",
      deck: "iPhone, Services and China all accelerated, but favorable tariff refunds supplied a meaningful part of the margin and EPS upside while R&D spending rose sharply.",
      summary: "Revenue rose 16% to $109.42 billion, gross margin reached 50.1% and diluted EPS rose 29% to $2.02. Tariff refunds added roughly two gross-margin points and $0.11 of EPS, while quarterly R&D reached $11.73 billion.",
      tags: ["Apple", "Services", "Earnings quality"],
      numbers: [
        { label: "Revenue", value: "$109.42B", change: "+16% YoY", tone: "up" },
        { label: "Diluted EPS", value: "$2.02", change: "+29% YoY", tone: "up" },
        { label: "Services", value: "$30.74B", change: "+12% YoY", tone: "up" },
        { label: "Gross margin", value: "50.1%", change: "refund boosted", tone: "flat" },
      ],
      sections: [
        {
          id: "mix",
          title: "The operating mix was broadly strong",
          paragraphs: [
            "iPhone revenue rose to $54.25 billion from $44.58 billion a year earlier, Services increased to $30.74 billion and Greater China reached $18.82 billion. Mac revenue rose to $10.35 billion, while iPad was the major product category that declined.",
            "Operating income increased to $35.70 billion and net income to $29.79 billion. Those figures show genuine operating momentum across hardware and recurring services, not merely a single-product pull-forward.",
          ],
        },
        {
          id: "quality",
          title: "The tariff refund changes the quality of the beat",
          paragraphs: [
            "Apple disclosed that favorable tariff refunds added about two percentage points to gross margin and $0.11 to diluted EPS. Removing that benefit does not erase the growth, but it lowers the repeatable baseline investors should carry into the next quarter.",
            "The distinction is important because hardware mix, component costs and tariffs can move gross margin quickly. A high-quality follow-through would preserve Services growth and product demand even if the refund contribution does not repeat.",
          ],
        },
        {
          id: "ai",
          title: "R&D is the visible AI investment channel",
          paragraphs: [
            "Quarterly research and development expense rose to $11.73 billion from $8.87 billion. Apple still does not carry the same owned-infrastructure burden as the hyperscalers, but its AI strategy is becoming more expensive through models, silicon, products and partnerships.",
            "Axios reported shares down about 4% after hours. The reaction suggests the market wants evidence that higher R&D produces upgrade demand, Services monetization or defensible device differentiation rather than only a strong reported quarter.",
          ],
          bullets: [
            "Services growth and gross margin without the tariff-refund benefit.",
            "Greater China demand after the fiscal Q3 acceleration.",
            "R&D conversion into device upgrades and paid services.",
            "Capital returns after the higher operating investment rate.",
          ],
        },
      ],
      sources: [
        {
          label: "Apple: fiscal third-quarter 2026 results",
          url: "https://www.apple.com/newsroom/2026/07/apple-reports-third-quarter-results/",
        },
        {
          label: "Apple: consolidated financial statements",
          url: "https://www.apple.com/newsroom/pdfs/fy2026q3/FY26_Q3_Consolidated_Financial_Statements.pdf",
        },
        {
          label: "Axios: Apple beat and tariff-refund contribution",
          url: "https://www.axios.com/2026/07/30/apple-earnings-beat-estimates-boosted-tariff-refunds",
        },
      ],
    },
    {
      id: "amazon-aws-capex-cashflow",
      page: "technology",
      category: "Cloud & AI Infrastructure",
      source: "Amazon + AP",
      sourceUrl: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
      updated: "Post-earnings",
      readTime: "6 min read",
      headline: "AWS grows 37%, but Amazon's free cash flow crosses below zero",
      deck: "The strongest AWS growth in 18 quarters validates AI demand. The same quarter shows why capital intensity, investment marks and cash conversion now belong beside revenue growth on the scorecard.",
      summary: "AWS revenue reached $42.23 billion and AWS operating income $16.62 billion. Amazon's trailing property spending climbed to $169.01 billion and free cash flow fell to negative $7.60 billion.",
      tags: ["Amazon", "AWS", "AI capex"],
      numbers: [
        { label: "AWS revenue", value: "$42.23B", change: "+37% YoY", tone: "up" },
        { label: "AWS op. income", value: "$16.62B", change: "39.4% margin", tone: "up" },
        { label: "TTM property spend", value: "$169.01B", change: "+64%", tone: "down" },
        { label: "TTM free cash", value: "-$7.60B", change: "was +$18.18B", tone: "down" },
      ],
      sections: [
        {
          id: "growth",
          title: "Demand caught up with the infrastructure story",
          paragraphs: [
            "AWS grew 37% to $42.23 billion, its fastest rate in 18 quarters. Operating income rose to $16.62 billion from $10.16 billion, producing a 39.4% segment margin even as Amazon expanded AI capacity.",
            "Management said the AWS AI business and custom-silicon business each exceed a $25 billion annual run rate. That is more useful than a generic AI-demand claim because it connects infrastructure, chips and customer consumption to current revenue.",
          ],
        },
        {
          id: "cash",
          title: "Cash conversion moved in the opposite direction",
          paragraphs: [
            "Trailing operating cash flow rose 33% to $161.40 billion, but property and equipment purchases rose faster to $169.01 billion. The result was negative $7.60 billion of trailing free cash flow, compared with positive $18.18 billion a year earlier.",
            "AP reported that Amazon now expects about $220 billion of capital spending in 2026, up from a prior $200 billion plan. The investment can create a larger future earnings pool, but it also increases exposure to utilization, depreciation schedules, power availability and customer concentration.",
          ],
        },
        {
          id: "quality",
          title: "Headline net income is not the operating scorecard",
          paragraphs: [
            "Net income of $62.65 billion included $53.4 billion of pre-tax non-operating income, primarily from the company's Anthropic investment. That mark is economically relevant, but it is not recurring retail or cloud operating profit.",
            "The cleaner scorecard is AWS growth and margin, consolidated operating income, operating cash flow and free cash flow after capital expenditures. Those measures show a business with stronger demand and operating leverage that is still consuming more cash to build the next layer of capacity.",
          ],
          bullets: [
            "AWS growth and backlog as new capacity becomes available.",
            "AWS margin after depreciation and power costs mature.",
            "Free cash flow after cash capex and equipment acquired under leases.",
            "Retail and advertising margins as funding buffers for the AI build.",
          ],
        },
      ],
      sources: [
        {
          label: "Amazon: second-quarter 2026 results",
          url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
        },
        {
          label: "AP: Amazon's AWS acceleration and investment plan",
          url: "https://apnews.com/article/b4ce02b4666a35b8975823c5c22072ee",
        },
      ],
    },
    {
      id: "bitcoin-yields-liquidity",
      page: "crypto",
      category: "Crypto",
      source: "CoinGecko + CoinDesk + Kraken",
      sourceUrl: "https://www.coingecko.com/en/coins/bitcoin",
      updated: "9:02 AM ET",
      readTime: "4 min read",
      headline: "Bitcoin slips below $64K into month-end derivatives settlement",
      deck: "Crypto is weakening against Thursday's equity rebound as the dollar and Treasury yields firm. Friday's monthly options and futures settlement can amplify flows, but the macro mix remains the more durable liquidity signal.",
      summary: "The 9:02 a.m. ET snapshot showed bitcoin at $63,696, ether at $1,880.98 and solana at $73.56, down 1.78%, 2.23% and 1.06% over 24 hours. The dollar index was up 0.49% and the 10-year yield was 4.70%.",
      tags: ["Bitcoin", "Options expiry", "Liquidity"],
      numbers: [
        { label: "Bitcoin", value: "$63,696", change: "-1.78% 24h", tone: "down" },
        { label: "Ethereum", value: "$1,880.98", change: "-2.23% 24h", tone: "down" },
        { label: "Solana", value: "$73.56", change: "-1.06% 24h", tone: "down" },
        { label: "U.S. Dollar", value: "100.35", change: "+0.49%", tone: "down" },
      ],
      sections: [
        {
          id: "spot",
          title: "Crypto is diverging from the prior cash-equity close",
          paragraphs: [
            "Bitcoin fell to $63,696 while ether declined to $1,880.98 and solana to $73.56. The broad decline contrasts with Thursday's 2.78% Nasdaq gain and 8.50% SOXX rebound, although those equity figures are prior cash closes rather than Friday trading.",
            "Ether's larger decline shows that weakness is not confined to bitcoin. The complex is trading as a higher-beta liquidity asset while dollar strength, a 4.70% 10-year yield and Brent above $90 compete with the positive AI-earnings impulse.",
          ],
        },
        {
          id: "expiry",
          title: "Month-end settlement can change flow without changing value",
          paragraphs: [
            "Kraken's July market calendar identifies July 31 as the monthly Deribit and CME bitcoin and ether options and futures settlement. Dealer hedging, rolling and basis trades can raise intraday sensitivity around the settlement window.",
            "Expiry is a timing variable, not a complete explanation. Without current venue-level open interest and strike concentration in the newsletter feed, it would be misleading to assign the price move to a particular wall or dealer-gamma level.",
          ],
        },
        {
          id: "macro",
          title: "The durable test remains cross-asset liquidity",
          paragraphs: [
            "The dollar index rose to 100.35, the 10-year yield held at 4.70% and gold fell 1.47% in the delayed Friday snapshot. That combination points to tighter dollar liquidity rather than a crypto-specific shock alone.",
            "A healthier turn would pair bitcoin stabilization with ether relative strength, a softer dollar and stable credit. A bounce driven only by post-expiry mechanical flows would be less persuasive without spot volume and ETF demand.",
          ],
          bullets: [
            "Bitcoin reclaiming $64,000 and then the recent $65,500 range high.",
            "Ether returning above $1,900 with improving relative strength.",
            "Dollar and Treasury-yield direction after the U.S. cash open.",
            "ETF flows, perpetual funding and venue open interest after settlement.",
          ],
        },
      ],
      sources: [
        {
          label: "CoinGecko: live bitcoin, ether and solana data",
          url: "https://www.coingecko.com/en/coins/bitcoin",
        },
        {
          label: "Kraken: July macro and crypto settlement calendar",
          url: "https://blog.kraken.com/economic-brief/july-22-2026",
        },
        {
          label: "CoinDesk: bitcoin option hedges into the Fed meeting",
          url: "https://www.coindesk.com/markets/2026/07/27/bitcoin-options-traders-are-dropping-their-hedges-going-into-the-fed-meeting",
        },
      ],
    },
    {
      id: "cot-dealer-positioning-july-21",
      page: "markets",
      category: "Positioning",
      source: "CFTC",
      sourceUrl: "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
      updated: "Friday morning official recheck",
      readTime: "3 min read",
      headline: "The July 21 COT file remains the positioning baseline",
      deck: "The July 21 report shows dealer/intermediary S&P net shorts growing while ICE WTI producer net length eased but remained positive.",
      summary: "Dealers are net short 724,971 consolidated S&P contracts, 7,392 more than the prior week. ICE WTI producers hold net length of 58,888 contracts, down 6,182. The report is weekly market structure, not an intraday signal.",
      tags: ["CFTC", "COT", "Positioning"],
      numbers: [
        { label: "Dealer S&P net", value: "-724,971", change: "-7,392 WoW", tone: "down" },
        { label: "WTI producer net", value: "+58,888", change: "-6,182 WoW", tone: "up" },
        { label: "Report date", value: "Jul 21", change: "released Friday", tone: "flat" },
      ],
      sections: [
        {
          id: "read",
          title: "What the report says",
          paragraphs: [
            "The CFTC's official files still carried a July 21 observation date when rechecked Friday morning. The new weekly report had not yet been posted, so the July 24 release remains the latest official dataset and no unverified July 28 position was substituted.",
            "In the Traders in Financial Futures file, S&P 500 consolidated dealer/intermediary longs were 149,182 contracts and shorts were 874,153, producing a net position of -724,971. The weekly net moved 7,392 contracts further short.",
            "In the disaggregated ICE light-sweet WTI row, producer/merchant longs were 403,188 contracts and shorts were 344,300, producing net length of +58,888. That net declined by 6,182 contracts week over week.",
          ],
        },
        {
          id: "use",
          title: "How to use weekly positioning",
          paragraphs: [
            "COT data is most useful when combined with price, volatility and liquidity. A crowded short can dampen or amplify movement depending on who must rebalance. It should never be read as a standalone entry signal.",
            "Dealer categories often include client hedges, and producer positions reflect commercial risk management. The direction and weekly change matter more than treating either category as a direct forecast of the next session's price.",
          ],
        },
      ],
      sources: [
        {
          label: "CFTC: July 21 Traders in Financial Futures file",
          url: "https://www.cftc.gov/dea/newcot/FinFutWk.txt",
        },
        {
          label: "CFTC: July 21 disaggregated futures file",
          url: "https://www.cftc.gov/dea/newcot/f_disagg.txt",
        },
      ],
    },
    {
      id: "oil-rebound-fed-transmission",
      page: "markets",
      category: "Energy & Margins",
      source: "AP + The Debrief",
      sourceUrl: "https://apnews.com/article/oil-companies-profits-exxon-chevron-9375fbf8f6f40426f7428e07d54000c7",
      updated: "9:02 AM ET",
      readTime: "5 min read",
      headline: "Exxon and Chevron turn the oil shock into a refining windfall",
      deck: "Surging crack spreads and constrained supply lifted profits sharply while WTI and Brent advanced again Friday. The gain supports energy cash flow but keeps the inflation and margin tax alive for the rest of the market.",
      summary: "AP reported Exxon second-quarter profit of $14.53 billion and Chevron profit of $12.07 billion. At 9:02 a.m. ET, delayed WTI was $85.38, up 2.14%, and Brent was $90.22, up 2.76%.",
      tags: ["Exxon", "Chevron", "Crude"],
      numbers: [
        { label: "WTI", value: "$85.38", change: "+2.14% delayed", tone: "down" },
        { label: "Brent", value: "$90.22", change: "+2.76% delayed", tone: "down" },
        { label: "Exxon profit", value: "$14.53B", change: "+105% YoY", tone: "up" },
        { label: "Chevron profit", value: "$12.07B", change: "+385% YoY", tone: "up" },
      ],
      sections: [
        {
          id: "results",
          title: "Refining converted scarcity into earnings",
          paragraphs: [
            "Exxon earned $14.53 billion in the second quarter, up 105% from a year earlier, on revenue of $116.02 billion. Chevron earned $12.07 billion, up 385%, on revenue of $70.06 billion, according to AP's report on the companies' releases.",
            "The operating driver was not only a higher crude benchmark. Conflict-related supply constraints widened refining margins, allowing integrated producers to capture value between crude input prices and finished products. That makes downstream utilization and crack spreads central to the quality of the profit surge.",
          ],
        },
        {
          id: "tape",
          title: "Friday's oil tape keeps the risk premium active",
          paragraphs: [
            "WTI rose to $85.38 and Brent to $90.22 in the delayed 9:02 a.m. ET snapshot. Natural gas was slightly lower, which narrows the inflation impulse, but oil remains the larger transport and industrial input for the current shock.",
            "The important variable is duration. A brief spike redistributes sector earnings; sustained Brent near or above $90 can raise inflation expectations, delay rate relief and force airlines, logistics companies, chemicals and consumer businesses to revise margins or prices.",
          ],
        },
        {
          id: "cross-asset",
          title: "The cross-asset transmission map",
          paragraphs: [
            "Energy producers and refiners gain cash flow, but the rest of the index faces a higher input-cost and discount-rate hurdle. The 10-year yield at 4.70% alongside rising crude is a less friendly combination for long-duration equities than oil strength with falling yields.",
            "Credit is the stress gauge. If high-yield spreads remain contained and small caps participate, the market can absorb an energy-led sector rotation. If oil, yields and the dollar rise together while credit weakens, the shock is becoming a broader financial-conditions event.",
          ],
          bullets: [
            "Crack spreads and refinery utilization after the current profit jump.",
            "Brent persistence above $90 and the 10-year yield around 4.70%.",
            "Airline, trucking, chemical and retailer guidance on cost pass-through.",
            "Credit spreads and consumer cyclicals as the broader stress test.",
          ],
        },
      ],
      sources: [
        {
          label: "AP: Exxon and Chevron second-quarter profits",
          url: "https://apnews.com/article/oil-companies-profits-exxon-chevron-9375fbf8f6f40426f7428e07d54000c7",
        },
        {
          label: "Yahoo Finance: delayed WTI futures",
          url: "https://finance.yahoo.com/quote/CL=F/",
        },
        {
          label: "Yahoo Finance: delayed Brent futures",
          url: "https://finance.yahoo.com/quote/BZ=F/",
        },
      ],
    },
    {
      id: "oil-volatility-vix-gap",
      page: "markets",
      category: "Options & Volatility",
      source: "Yahoo Finance + The Debrief",
      sourceUrl: "https://finance.yahoo.com/quote/%5EVIX/",
      updated: "9:02 AM ET",
      readTime: "5 min read",
      headline: "VIX is current at 17.24; gamma and flow tables remain historical",
      deck: "The volatility and cross-asset feeds refreshed Friday morning, but the market endpoint again returned no current gainers, losers or option rows. The displayed gamma, walls and activity table remain an expired July 24 reference, not a Friday signal.",
      summary: "The delayed VIX read was 17.24 at 9:02 a.m. ET. The retained -$3.96 billion SPX gamma estimate, 7,454 zero-gamma level and 1.17 put/call ratio were captured July 24 for contracts that expired July 27.",
      tags: ["VIX", "Gamma", "Data quality"],
      numbers: [
        { label: "VIX", value: "17.24", change: "+0.88% delayed", tone: "flat" },
        { label: "S&P 500", value: "7,437.63", change: "prior close", tone: "up" },
        { label: "Current chain", value: "Unavailable", change: "9:02 AM ET", tone: "flat" },
        { label: "SPX gamma", value: "-$3.96B", change: "expired fallback", tone: "down" },
      ],
      sections: [
        {
          id: "divergence",
          title: "What can be trusted this morning",
          paragraphs: [
            "The live cross-asset endpoint continues to return mixed-timestamp cash closes, futures, rates, currencies and crypto. It showed VIX at 17.24, the 10-year yield at 4.70% and bitcoin near $63,696 before the U.S. open. The S&P 500 and ETF rows still represent Thursday's close.",
            "The separate serverless market endpoint returned no current gainers, losers or option rows at 9:02 a.m. ET. Without a fresh chain containing strike, expiration, implied volatility, open interest and volume, the newsletter cannot publish defensible gamma exposure, put/call or unusual-flow estimates for Friday.",
          ],
        },
        {
          id: "gamma",
          title: "How dealer gamma changes the path",
          paragraphs: [
            "The July 24 analytical snapshot was short gamma below the estimated 7,454 zero-gamma level. Its highest open-interest walls within 5% of spot were near 7,630 for calls and 7,200 for puts, with a model-implied July 27 move of roughly 0.7%. Those contracts have expired, so the levels describe a prior positioning regime and do not govern Friday's intraday tape.",
            "Gamma estimates are model-based and depend on delayed open interest and implied volatility. They are best used as a map of potential sensitivity, not as a claim about any dealer's exact book.",
          ],
        },
        {
          id: "signals",
          title: "Confirmation signals",
          bullets: [
            "VIX term structure, skew and opening realized volatility, not only the spot VIX quote.",
            "SOXX breadth, high-yield spreads and Treasury volatility together.",
            "A fresh SPX chain with open interest and implied volatility before assigning new gamma walls.",
            "Whether U.S. volume confirms Thursday's Microsoft and semiconductor rebound.",
          ],
        },
      ],
      sources: [
        {
          label: "Yahoo Finance: delayed VIX market data",
          url: "https://finance.yahoo.com/quote/%5EVIX/",
        },
        {
          label: "Saxo: chips cool volatility while oil lifts yields",
          url: "https://www.home.saxo/en-gb/content/articles/options/options-brief---chips-cool-vol-oil-lifts-yields---22-july-2026-22072026",
        },
        {
          label: "Yahoo Finance: SPX market and options data",
          url: "https://finance.yahoo.com/quote/%5ESPX/",
        },
        {
          label: "Alpaca: options market data methodology",
          url: "https://docs.alpaca.markets/us/reference/optionchain",
        },
      ],
    },
    {
      id: "friday-catalyst-desk",
      page: "markets",
      category: "Friday Catalyst Desk",
      source: "BLS + Kiplinger + Company filings",
      sourceUrl: "https://www.bls.gov/news.release/eci.nr0.htm",
      updated: "9:15 AM ET",
      readTime: "5 min read",
      headline: "Friday's decision tree runs from labor costs to business activity",
      deck: "The ECI has already kept rate pressure alive. Chicago PMI, revised consumer sentiment, the energy rig count and the cash-market response to Apple and Amazon now determine whether Thursday's rebound broadens or concentrates.",
      summary: "Civilian compensation rose 0.9% quarter over quarter at 8:30 a.m. ET. Chicago PMI follows at 9:45, revised University of Michigan sentiment at 10:00 and the Baker Hughes rig count at 1:00 p.m.",
      tags: ["Calendar", "ECI", "Earnings"],
      numbers: [
        { label: "ECI", value: "8:30 ET", change: "+0.9% Q/Q", tone: "down" },
        { label: "Chicago PMI", value: "9:45 ET", change: "activity", tone: "flat" },
        { label: "UMich final", value: "10:00 ET", change: "sentiment", tone: "flat" },
        { label: "Rig count", value: "1:00 ET", change: "energy supply", tone: "flat" },
      ],
      sections: [
        {
          id: "known",
          title: "What is already known",
          paragraphs: [
            "The ECI rose 0.9% in the second quarter and 3.4% over 12 months. That is gradual annual cooling without a decisive quarterly break, and the 10-year yield reached 4.70% in the delayed morning feed.",
            "Amazon delivered 37% AWS growth but negative trailing free cash flow after $169.01 billion of property spending. Apple delivered 16% revenue growth, but tariff refunds boosted gross margin and EPS. Friday's market must price both growth and repeatability.",
          ],
        },
        {
          id: "remaining",
          title: "What remains on the calendar",
          paragraphs: [
            "Chicago PMI provides a regional manufacturing and business-activity signal at 9:45 a.m. ET. The final University of Michigan reading at 10:00 adds consumer sentiment and inflation-expectation context after the quarter's labor-cost data.",
            "The Baker Hughes rig count at 1:00 p.m. matters because WTI is above $85 and Brent above $90. A supply response that remains muted can extend the energy risk premium; faster drilling would be a slower-moving normalization signal.",
          ],
        },
        {
          id: "decision-tree",
          title: "The decision tree for the close",
          bullets: [
            "Risk-on confirmation: semiconductors, software, small caps and credit advance together.",
            "Concentrated rebound: Amazon supports indices while Apple and equal-weight breadth lag.",
            "Rate pressure: the 10-year rises through 4.70% as activity data stay firm.",
            "Growth scare: activity softens while credit and consumer cyclicals weaken despite lower yields.",
          ],
        },
      ],
      sources: [
        {
          label: "BLS: second-quarter Employment Cost Index",
          url: "https://www.bls.gov/news.release/eci.nr0.htm",
        },
        {
          label: "Kiplinger: this week's economic calendar",
          url: "https://www.kiplinger.com/investing/economy/this-weeks-economic-calendar",
        },
        {
          label: "Apple: fiscal third-quarter results",
          url: "https://www.apple.com/newsroom/2026/07/apple-reports-third-quarter-results/",
        },
        {
          label: "Amazon: second-quarter results",
          url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
        },
      ],
    },
    {
      id: "microsoft-meta-ai-return-split",
      page: "technology",
      category: "AI Earnings",
      source: "Microsoft + Meta + AP",
      sourceUrl: "https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q4/press-release-webcast",
      updated: "Friday follow-through",
      readTime: "6 min read",
      headline: "Azure clears the AI hurdle; Meta's free cash flow absorbs the spending bill",
      deck: "Both companies produced strong demand, but the cash economics separated them. Microsoft paired 43% Azure growth with a much larger backlog, while Meta's 28% revenue growth arrived beside 55% cost growth and only $784 million of free cash flow.",
      summary: "Microsoft reported $90.0 billion of revenue and $40.6 billion of operating income. Meta reported $60.80 billion of revenue and $18.78 billion of operating income after $42.03 billion of costs; its quarterly capital spending and lease payments reached $31.08 billion.",
      tags: ["Microsoft", "Meta", "AI capex"],
      numbers: [
        { label: "Azure", value: "+43%", change: "YoY", tone: "up" },
        { label: "MSFT cRPO", value: "$678B", change: "+84% YoY", tone: "up" },
        { label: "META revenue", value: "$60.80B", change: "+28% YoY", tone: "up" },
        { label: "META free cash", value: "$784M", change: "Q2", tone: "down" },
      ],
      sections: [
        {
          id: "microsoft",
          title: "Microsoft converted capacity into visible demand",
          paragraphs: [
            "Microsoft's fiscal fourth-quarter revenue rose 18% to $90.0 billion and operating income rose 18% to $40.6 billion. Microsoft Cloud revenue reached $59.3 billion, up 27%, while Azure and other cloud services grew 43%.",
            "The forward signal was commercial remaining performance obligation, up 84% to $678 billion. Management also said annual Azure revenue surpassed $100 billion and Microsoft 365 Copilot exceeded 30 million paid seats. Those metrics connect infrastructure to contracted demand and paid adoption.",
            "GAAP EPS of $4.81 included discrete items, including a $3.2 billion Anthropic investment gain. Non-GAAP EPS was $4.74, so operating income, cloud growth and backlog are cleaner measures of the recurring quarter than the investment mark.",
          ],
        },
        {
          id: "meta",
          title: "Meta grew demand, but cash conversion broke lower",
          paragraphs: [
            "Meta's revenue rose 28% to $60.80 billion. Ad impressions increased 14%, average price per ad rose 12% and Family daily active people reached 3.60 billion, up 3%. The demand engine was not the problem.",
            "Costs and expenses rose 55% to $42.03 billion, operating income fell 8% to $18.78 billion and net income declined 14%. After $30.12 billion of property and equipment purchases and $962 million of finance-lease principal payments, free cash flow was only $784 million.",
            "Meta narrowed 2026 capital-spending guidance to $130 billion-$145 billion and expects third-quarter revenue of $61 billion-$64 billion. The market now needs proof that AI-driven ad yield and engagement can scale faster than depreciation, infrastructure and model-development costs.",
          ],
        },
        {
          id: "verdict",
          title: "The market rewarded evidence, not the label AI",
          paragraphs: [
            "Microsoft closed Thursday up 15.5%, its best day in nearly 18 years, while Meta fell about 8%. The split is a useful capital-allocation verdict: the market will fund large spending when contracted demand, utilization and paid products are visible, but it will discount growth when cash conversion deteriorates sharply.",
            "Amazon's 37% AWS growth strengthens the demand side of that verdict, while its negative trailing free cash flow keeps capital intensity in view. Apple's result shows a different model: less owned infrastructure, but higher R&D and an earnings beat whose quality was helped by tariff refunds.",
          ],
          bullets: [
            "Backlog and utilization moving with, not behind, installed capacity.",
            "Paid seats, consumption or ad yield that can be tied to AI deployment.",
            "Free cash flow after cash capex and finance leases.",
            "Operating margin after depreciation, model training and employee costs.",
          ],
        },
      ],
      sources: [
        {
          label: "Microsoft: fiscal Q4 2026 results and financial tables",
          url: "https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q4/press-release-webcast",
        },
        {
          label: "Meta: Q2 2026 results and cash-flow reconciliation",
          url: "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-Second-Quarter-2026-Results/default.aspx",
        },
        {
          label: "AP: Microsoft, Meta and Thursday's market close",
          url: "https://apnews.com/article/stock-markets-rates-korea-ai-oil-99b5702d93a2b5c6e513fb952ccdcc92",
        },
      ],
    },
    {
      id: "flashattention-blackwell-efficiency",
      page: "technology",
      category: "AI Systems Research",
      source: "arXiv",
      sourceUrl: "https://arxiv.org/abs/2603.05451",
      updated: "Research desk",
      readTime: "5 min read",
      headline: "FlashAttention-4 shows why AI performance is becoming a systems problem",
      deck: "Algorithm and kernel co-design is extracting more useful output from Blackwell-class hardware.",
      summary: "FlashAttention-4 reports up to 1.3x performance over cuDNN 9.13 and 2.7x over Triton on B200 hardware for tested workloads. The investment read-through is that software efficiency can alter effective compute supply.",
      tags: ["FlashAttention", "Blackwell", "Efficiency"],
      numbers: [
        { label: "Peak result", value: "1,613 TFLOPs/s", change: "reported", tone: "up" },
        { label: "Utilization", value: "71%", change: "reported", tone: "up" },
        { label: "vs. Triton", value: "2.7x", change: "tested", tone: "up" },
      ],
      sections: [
        {
          id: "bottleneck",
          title: "The bottleneck moved",
          paragraphs: [
            "Blackwell increases tensor throughput faster than several surrounding resources. That asymmetry means kernels designed for an earlier hardware balance leave performance unused.",
            "The paper redesigns pipelines, softmax rescaling and memory movement around the new bottlenecks. The result is a reminder that headline chip specifications do not equal delivered application performance.",
          ],
        },
        {
          id: "economics",
          title: "The economic read-through",
          paragraphs: [
            "Higher utilization lowers cost per useful token and can partially offset the capital burden of AI infrastructure. It may also increase demand by making previously uneconomic workloads viable.",
            "For hardware companies, better software can expand the addressable market while reducing the number of chips required for a fixed workload. Both effects matter when translating benchmark gains into revenue.",
          ],
        },
        {
          id: "questions",
          title: "Questions for investors",
          bullets: [
            "How quickly do framework and cloud providers integrate the kernels?",
            "Do benchmark gains persist across model sizes and production constraints?",
            "Who captures the savings: vendors, cloud platforms or end customers?",
            "Does efficiency expand demand faster than it reduces hardware per workload?",
          ],
        },
      ],
      sources: [
        {
          label: "arXiv: FlashAttention-4",
          url: "https://arxiv.org/abs/2603.05451",
        },
      ],
    },
    {
      id: "bitcoin-etf-carry-arbitrage",
      page: "crypto",
      category: "Crypto Market Structure",
      source: "arXiv + CoinDesk",
      sourceUrl: "https://arxiv.org/abs/2605.29309",
      updated: "Research desk",
      readTime: "5 min read",
      headline: "ETF inflows do not remove the limits to bitcoin arbitrage",
      deck: "A recent paper uses ETF holdings, options and CME futures to measure carry across segmented bitcoin markets.",
      summary: "The ETF wrapper has deepened institutional access, but options, futures and spot markets still clear through different balance sheets. Implied carry can reveal when funding and arbitrage capacity are under strain.",
      tags: ["Bitcoin ETF", "Carry", "Arbitrage"],
      numbers: [
        { label: "ETF streak", value: "7 sessions", change: "inflows", tone: "up" },
        { label: "Flow", value: "Nearly $1B", change: "reported", tone: "up" },
        { label: "Bitcoin", value: "$64,058", change: "-0.94%", tone: "down" },
      ],
      sections: [
        {
          id: "measurement",
          title: "What the paper measures",
          paragraphs: [
            "Put-call parity can recover an options-implied forward price. ETF holdings translate each share into bitcoin exposure, while CME futures provide a regulated term structure. Comparing the three creates a common carry framework.",
            "Persistent gaps point to capital, funding, settlement or mandate constraints rather than a free arbitrage that can be closed instantly.",
          ],
        },
        {
          id: "flows",
          title: "Why the inflow streak still matters",
          paragraphs: [
            "ETF demand creates a recurring source of spot-linked buying and can stabilize the investor base. It does not make bitcoin independent of dollar liquidity, Treasury yields or derivatives positioning.",
            "A strong flow tape with weak price response can indicate offsetting supply or expensive carry. Strong price response with widening carry can indicate leverage entering faster than arbitrage balance sheet.",
          ],
        },
        {
          id: "monitor",
          title: "A practical monitor",
          bullets: [
            "ETF creations and redemptions alongside spot price response.",
            "CME basis and options-implied forwards.",
            "Funding rates and open interest on crypto-native venues.",
            "Cross-asset liquidity through the dollar and Treasury yields.",
          ],
        },
      ],
      sources: [
        {
          label: "arXiv: Implied ETF carry rates and limits of arbitrage",
          url: "https://arxiv.org/abs/2605.29309",
        },
        {
          label: "CoinDesk: seven-session bitcoin ETF inflow streak",
          url: "https://www.coindesk.com/daybook-us/2026/07/23/bulls-face-a-test-unlike-anything-in-bitcoin-s-17-year-history",
        },
      ],
    },
  ],

  timeline: [
    {
      time: "Fri · 8:30 ET",
      title: "Employment costs rise 0.9%",
      detail: "Civilian compensation rose 0.9% in Q2 and 3.4% over 12 months, keeping labor-cost persistence in the rate debate.",
      url: "https://www.bls.gov/news.release/eci.nr0.htm",
    },
    {
      time: "Fri · Open",
      title: "Apple and Amazon meet the cash market",
      detail: "AWS growth accelerated to 37%; Apple posted 16% revenue growth with tariff refunds adding about two gross-margin points.",
      url: "https://ir.aboutamazon.com/news-release/news-release-details/2026/Amazon-com-Announces-Second-Quarter-Results/default.aspx",
    },
    {
      time: "Fri · 9:45 ET",
      title: "Chicago PMI tests business activity",
      detail: "The regional activity reading follows a firm labor-cost print and will help separate inflation pressure from a broader growth slowdown.",
      url: "https://www.kiplinger.com/investing/economy/this-weeks-economic-calendar",
    },
    {
      time: "Fri · 10:00 ET",
      title: "Final consumer sentiment arrives",
      detail: "The revised University of Michigan release adds consumer-demand and inflation-expectation context to the morning's market move.",
      url: "https://www.kiplinger.com/investing/economy/this-weeks-economic-calendar",
    },
    {
      time: "Fri · 1:00 ET",
      title: "Rig count maps the supply response",
      detail: "Baker Hughes data matter with WTI above $85 and Brent above $90 after sharply higher integrated-oil profits.",
      url: "https://www.kiplinger.com/investing/economy/this-weeks-economic-calendar",
    },
  ],

  marketDrivers: [
    {
      title: "AI monetization",
      state: "AWS +37%",
      detail: "Cloud revenue accelerated and segment margin reached 39.4%, validating installed capacity.",
      tone: "up",
    },
    {
      title: "Earnings quality",
      state: "AAPL refund boost",
      detail: "Tariff refunds added about two gross-margin points and $0.11 of EPS.",
      tone: "flat",
    },
    {
      title: "Labor and rates",
      state: "ECI +0.9% / 10Y 4.70%",
      detail: "Compensation remained firm enough to keep duration pressure active.",
      tone: "down",
    },
    {
      title: "Energy and liquidity",
      state: "Brent $90.22",
      detail: "Oil and the dollar rose while gold and crypto weakened in the Friday morning snapshot.",
      tone: "down",
    },
  ],

  techMatrix: [
    {
      company: "Amazon",
      focus: "AWS acceleration versus infrastructure cash cost",
      signal: "AWS +37%; TTM free cash flow -$7.60B",
      tone: "up",
    },
    {
      company: "Apple",
      focus: "Product and Services growth versus repeatable margin",
      signal: "Revenue +16%; tariff refunds boosted EPS $0.11",
      tone: "flat",
    },
    {
      company: "Microsoft",
      focus: "Azure, Copilot and contracted cloud demand",
      signal: "Azure +43%; shares +15.5% Thursday",
      tone: "up",
    },
    {
      company: "Meta",
      focus: "Ad growth versus infrastructure cash cost",
      signal: "Revenue +28%; shares -8% Thursday",
      tone: "down",
    },
    {
      company: "Semiconductors",
      focus: "AI demand versus two-day positioning reversal",
      signal: "SOXX +8.50% Thursday after -5.38% Wednesday",
      tone: "flat",
    },
  ],

  podcasts: [
    {
      title: "All-In",
      focus: "Macro, policy, venture and technology",
      cadence: "Weekly",
      url: "https://podcasts.apple.com/us/search?term=All-In%20Podcast",
    },
    {
      title: "Acquired",
      focus: "Company strategy and business history",
      cadence: "Long-form",
      url: "https://podcasts.apple.com/us/search?term=Acquired",
    },
    {
      title: "Prof G Markets",
      focus: "Markets, business and capital allocation",
      cadence: "Weekly",
      url: "https://podcasts.apple.com/us/search?term=Prof%20G%20Markets",
    },
    {
      title: "Odd Lots",
      focus: "Market structure, liquidity and macro",
      cadence: "Twice weekly",
      url: "https://podcasts.apple.com/us/search?term=Odd%20Lots",
    },
    {
      title: "Masters in Business",
      focus: "Investors, operators and market history",
      cadence: "Weekly",
      url: "https://podcasts.apple.com/us/search?term=Masters%20in%20Business",
    },
    {
      title: "Macro Voices",
      focus: "Rates, commodities and global macro",
      cadence: "Weekly",
      url: "https://podcasts.apple.com/us/search?term=Macro%20Voices",
    },
    {
      title: "Invest Like the Best",
      focus: "Business quality and investing frameworks",
      cadence: "Weekly",
      url: "https://podcasts.apple.com/us/search?term=Invest%20Like%20the%20Best",
    },
    {
      title: "BG2Pod",
      focus: "AI infrastructure and technology strategy",
      cadence: "Periodic",
      url: "https://podcasts.apple.com/us/search?term=BG2Pod",
    },
  ],

  research: [
    {
      category: "AI Economics",
      kind: "Working paper",
      year: "2026",
      title: "The AI Investment Race",
      authors: "Phurichai Rungcharoenkitkul",
      source: "BIS",
      url: "https://www.bis.org/publ/work1367.htm",
      summary: "Models the AI buildout as a winner-take-most contest in which firms can over-commit capital, then adds debt and circular equity ties to study fire-sale and contagion risk.",
      relevance: "A timely framework for separating productive AI investment from financing structures that can amplify disappointment across specialized assets.",
    },
    {
      category: "Options",
      kind: "Working paper",
      year: "2026",
      title: "Pin Risk, Jumps, and Option Trading",
      authors: "Nicholas G. Polson and Vadim Sokolov",
      source: "SSRN",
      url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6910798",
      summary: "Connects expiry pin risk, stochastic and rough volatility, scheduled and unscheduled jumps, and practical covered-call management in single-name options.",
      relevance: "Explains why delta-gamma summaries can fail near expiry or earnings and why option overlays need event-aware sizing and rolling rules.",
    },
    {
      category: "Portfolio Risk",
      kind: "Paper",
      year: "2016",
      title: "Volatility Managed Portfolios",
      authors: "Alan Moreira and Tyler Muir",
      source: "NBER",
      url: "https://www.nber.org/papers/w22208",
      summary: "Tests portfolios that reduce exposure when volatility rises and documents improved risk-adjusted outcomes across several factors and asset classes.",
      relevance: "A foundation for volatility targeting, risk budgeting and the risk calculator in The Debrief.",
    },
    {
      category: "Options",
      kind: "Paper",
      year: "2024",
      title: "Construction and Hedging of Equity Index Options Portfolios",
      authors: "Maciej Wysocki and Robert Ślepaczuk",
      source: "arXiv",
      url: "https://arxiv.org/abs/2407.13908",
      summary: "Compares systematic S&P 500 option-writing and hedging strategies using Black-Scholes-Merton and Variance-Gamma models with transaction costs.",
      relevance: "Connects option Greeks, hedge frequency, volatility and sizing to actual portfolio construction.",
    },
    {
      category: "Market Structure",
      kind: "Working paper",
      year: "2026 revision",
      title: "Through Stormy Seas: How Fragile Is Liquidity Across Asset Classes and Time?",
      authors: "Nihad Aliyev, Matteo Aquilina, Khaladdin Rzayev and Sonya Zhu",
      source: "BIS",
      url: "https://www.bis.org/publ/work1229.htm",
      summary: "Studies the distribution and resilience of liquidity across equities, foreign exchange and government bonds over 25 years.",
      relevance: "Explains why average spreads can look healthy while tail liquidity and market fragility worsen.",
    },
    {
      category: "Banking",
      kind: "Working paper",
      year: "2026",
      title: "Liquidity Regulation and Bank Funding Costs",
      authors: "Iñaki Aldasoro, Sebastian Doerr and Haonan Zhou",
      source: "BIS",
      url: "https://www.bis.org/publ/work1352.htm",
      summary: "Provides causal evidence on how the Liquidity Coverage Ratio affected bank borrowing costs and maturity from money market funds.",
      relevance: "Useful for reading bank funding stress, balance-sheet resilience and credit transmission.",
    },
    {
      category: "Currencies",
      kind: "Policy report",
      year: "2026",
      title: "Foreign Currency Funding Risk and Cross-Border Liquidity",
      authors: "CGFS Working Group",
      source: "BIS",
      url: "https://www.bis.org/publ/cgfs71.htm",
      summary: "Maps foreign-currency funding mismatches, internal capital markets, derivatives hedges and central-bank liquidity facilities.",
      relevance: "A practical framework for dollar funding risk and cross-currency stress.",
    },
    {
      category: "Crypto",
      kind: "Paper",
      year: "2026",
      title: "Implied ETF Carry Rates and the Limits of Arbitrage in Segmented Bitcoin Markets",
      authors: "Mindy L. Mallory",
      source: "arXiv",
      url: "https://arxiv.org/abs/2605.29309",
      summary: "Combines ETF holdings, options-implied forwards and CME futures to compare carry across segmented bitcoin markets.",
      relevance: "Turns ETF flows into a market-structure and funding analysis rather than a single headline number.",
    },
    {
      category: "Crypto",
      kind: "Paper",
      year: "2026",
      title: "Do Prediction Markets Forecast Cryptocurrency Volatility? Evidence from Kalshi Macro Contracts",
      authors: "Hardhik Mohanty and Bhaskar Krishnamachari",
      source: "arXiv",
      url: "https://arxiv.org/abs/2604.01431",
      summary: "Tests whether changes in Kalshi probabilities for Fed, recession and CPI outcomes forecast realized volatility across bitcoin and five altcoins.",
      relevance: "Shows that recession probabilities added out-of-sample information for bitcoin volatility while CPI repricing improved forecasts for ether and solana, with important regime limits.",
    },
    {
      category: "Financial AI",
      kind: "Benchmark paper",
      year: "2026",
      title: "Earnings25: A Comprehensive 500-Hour Speech Benchmark for Finance",
      authors: "Denglin Jiang and coauthors",
      source: "arXiv",
      url: "https://arxiv.org/abs/2607.23813",
      summary: "Introduces 498 hours of full S&P 500 earnings calls plus a 46-hour, 290-industry segmented test set with aligned transcripts, speaker roles and reproducible ASR baselines.",
      relevance: "Shows why finance-specific jargon, numeracy, accents and overlapping Q&A can make automated earnings-call transcripts materially less reliable than aggregate word-error rates suggest.",
    },
    {
      category: "AI Economics",
      kind: "Paper",
      year: "2020",
      title: "Scaling Laws for Neural Language Models",
      authors: "Jared Kaplan and coauthors",
      source: "arXiv",
      url: "https://arxiv.org/abs/2001.08361",
      summary: "Documents power-law relationships between language-model loss, model size, data and compute.",
      relevance: "Provides the economic logic behind AI infrastructure demand and the importance of compute efficiency.",
    },
    {
      category: "AI Economics",
      kind: "Paper",
      year: "2026",
      title: "The Unreasonable Effectiveness of Scaling Laws in AI",
      authors: "Chien-Ping Lu",
      source: "arXiv",
      url: "https://arxiv.org/abs/2603.28507",
      summary: "Argues that scaling laws remain useful because logical compute abstracts away implementation details while efficiency keeps improving.",
      relevance: "Links declining model-loss returns with pressure for lower cost per token and systems innovation.",
    },
    {
      category: "AI Systems",
      kind: "Technical paper",
      year: "2026",
      title: "FlashAttention-4: Algorithm and Kernel Pipelining Co-Design for Asymmetric Hardware Scaling",
      authors: "Ted Zadouri, Markus Hoehnerbach, Jay Shah, Timmy Liu, Vijay Thakkar and Tri Dao",
      source: "arXiv",
      url: "https://arxiv.org/abs/2603.05451",
      summary: "Redesigns attention kernels for Blackwell bottlenecks and reports higher utilization and throughput.",
      relevance: "Shows how software can change effective accelerator supply, cost and competitive positioning.",
    },
    {
      category: "AI Systems",
      kind: "Foundational paper",
      year: "2017",
      title: "Attention Is All You Need",
      authors: "Ashish Vaswani and coauthors",
      source: "arXiv",
      url: "https://arxiv.org/abs/1706.03762",
      summary: "Introduces the Transformer architecture based on attention rather than recurrence or convolution.",
      relevance: "The architectural starting point for the modern accelerator, memory and networking demand stack.",
    },
    {
      category: "Asset Pricing",
      kind: "Paper",
      year: "2020",
      title: "Deep Learning in Asset Pricing",
      authors: "Luyang Chen, Markus Pelger and Jason Zhu",
      source: "Review of Financial Studies",
      url: "https://doi.org/10.1093/rfs/hhaa009",
      summary: "Uses deep neural networks to estimate asset-pricing models and the economic structure of the stochastic discount factor.",
      relevance: "A rigorous reference for machine learning in return prediction and factor construction.",
    },
    {
      category: "Options",
      kind: "Foundational paper",
      year: "1973",
      title: "The Pricing of Options and Corporate Liabilities",
      authors: "Fischer Black and Myron Scholes",
      source: "Journal of Political Economy",
      url: "https://doi.org/10.1086/260062",
      summary: "Derives the option-pricing framework that remains the baseline for pricing and Greek-based risk analysis.",
      relevance: "The mathematical foundation behind The Debrief options calculator, with real-world limitations stated clearly.",
    },
  ],

  sectorMap: [
    { sector: "Technology", signal: "Return test", driver: "AWS +37% and Microsoft +15.5% reward visible AI revenue; Apple and Meta expose quality gaps", tone: "up" },
    { sector: "Semiconductors", signal: "Sharp repair", driver: "SOXX rose 8.50% Thursday after Wednesday's 5.38% decline", tone: "flat" },
    { sector: "Financials", signal: "Rate-sensitive", driver: "ECI +0.9% quarter over quarter and the 10-year near 4.70%", tone: "down" },
    { sector: "Industrials", signal: "Activity test", driver: "Chicago PMI follows firm labor costs at 9:45 AM ET", tone: "flat" },
    { sector: "Energy", signal: "Profit windfall", driver: "WTI $85.38, Brent $90.22 and sharply higher Exxon and Chevron profit", tone: "up" },
    { sector: "Consumer", signal: "Purchasing-power squeeze", driver: "Private real wages fell 0.4% year over year despite nominal wage growth", tone: "down" },
    { sector: "Healthcare", signal: "Relative defense", driver: "Lower AI-capex sensitivity offsets pressure from higher rates and energy", tone: "up" },
  ],

  cot: {
    date: "Tuesday, July 21, 2026",
    note: "Latest official weekly report, released Friday, July 24 and rechecked against the CFTC's TFF and disaggregated futures files at 9:05 AM ET Friday. The new weekly report was not yet posted; both official files still carried the July 21 observation date.",
    rows: [
      {
        market: "S&P 500",
        group: "Dealer / intermediary",
        net: -724971,
        read: "Net shorts increased by 7,392 contracts week over week.",
      },
      {
        market: "WTI crude",
        group: "Producer / merchant",
        net: 58888,
        read: "ICE WTI producer net length fell by 6,182 contracts but remains positive.",
      },
    ],
  },

  fallbackMarket: {
    capturedAt: "2026-07-24T21:26:36.000Z",
    gainers: [
      { symbol: "RNG", name: "RingCentral, Inc.", price: 48.31, change: 25.09 },
      { symbol: "THC", name: "Tenet Healthcare Corporation", price: 233.2, change: 17.17 },
      { symbol: "FRMI", name: "Fermi Inc.", price: 7.4, change: 17.09 },
      { symbol: "IP", name: "International Paper Company", price: 42.16, change: 11.21 },
      { symbol: "SW", name: "Smurfit WestRock plc", price: 48.56, change: 11.1 },
      { symbol: "SLB", name: "SLB Limited", price: 52.42, change: 11.01 },
      { symbol: "DLR", name: "Digital Realty Trust, Inc.", price: 199.08, change: 11.01 },
      { symbol: "SSNC", name: "SS&C Technologies Holdings, Inc.", price: 73.88, change: 10.35 },
    ],
    losers: [
      { symbol: "MXL", name: "MaxLinear, Inc.", price: 71.59, change: -21.54 },
      { symbol: "NBIS", name: "Nebius Group N.V.", price: 187.77, change: -15.02 },
      { symbol: "BE", name: "Bloom Energy Corporation", price: 184.89, change: -14.91 },
      { symbol: "HIMS", name: "Hims & Hers Health, Inc.", price: 28.09, change: -14.2 },
      { symbol: "AEHR", name: "Aehr Test Systems", price: 76.32, change: -13.77 },
      { symbol: "NVCR", name: "NovoCure Limited", price: 17.65, change: -11.71 },
      { symbol: "LBRT", name: "Liberty Energy Inc.", price: 17.36, change: -11.52 },
      { symbol: "CRWV", name: "CoreWeave, Inc.", price: 71.88, change: -11.37 },
    ],
    optionsDesk: {
      underlying: "^SPX",
      spot: 7411.98,
      expiration: "2026-07-27",
      asOf: "2026-07-24T21:26:36.000Z",
      netGammaBillions: -3.96,
      zeroGamma: 7454,
      callWall: 7630,
      putWall: 7200,
      expectedMovePercent: 0.7,
      putCallRatio: 1.17,
      totalWatchlistVolume: 3144763,
      sentiment: "Defensive",
      gammaByStrike: [
        { strike: 7455, exposure: 0.005 },
        { strike: 7450, exposure: -0.63 },
        { strike: 7445, exposure: -0.099 },
        { strike: 7440, exposure: 0.024 },
        { strike: 7435, exposure: -0.017 },
        { strike: 7430, exposure: -0.04 },
        { strike: 7425, exposure: -0.215 },
        { strike: 7420, exposure: 0.013 },
        { strike: 7415, exposure: -0.025 },
        { strike: 7410, exposure: -0.218 },
        { strike: 7405, exposure: -0.004 },
        { strike: 7400, exposure: -0.314 },
        { strike: 7395, exposure: -0.054 },
        { strike: 7390, exposure: 0.015 },
        { strike: 7385, exposure: -0.03 },
        { strike: 7380, exposure: -0.055 },
        { strike: 7375, exposure: -0.119 },
        { strike: 7370, exposure: -0.072 },
        { strike: 7365, exposure: -0.024 },
      ],
      activity: [
        { symbol: "^SPX", contract: "SPXW260727P07400000", side: "Put", strike: 7400, expiration: "2026-07-27", volume: 12591, openInterest: 1191, volumeOpenInterest: 10.57, premium: 27826110, impliedVolatility: 10.4 },
        { symbol: "SPY", contract: "SPY260727P00739000", side: "Put", strike: 739, expiration: "2026-07-27", volume: 86279, openInterest: 2367, volumeOpenInterest: 36.45, premium: 24071841, impliedVolatility: 10.3 },
        { symbol: "SPY", contract: "SPY260727P00740000", side: "Put", strike: 740, expiration: "2026-07-27", volume: 71031, openInterest: 4447, volumeOpenInterest: 15.97, premium: 23227137, impliedVolatility: 10.3 },
        { symbol: "QQQ", contract: "QQQ260727P00690000", side: "Put", strike: 690, expiration: "2026-07-27", volume: 29770, openInterest: 6010, volumeOpenInterest: 4.95, premium: 21538595, impliedVolatility: 15.5 },
        { symbol: "QQQ", contract: "QQQ260727P00685000", side: "Put", strike: 685, expiration: "2026-07-27", volume: 44059, openInterest: 5651, volumeOpenInterest: 7.8, premium: 20156993, impliedVolatility: 17 },
        { symbol: "SPY", contract: "SPY260727P00738000", side: "Put", strike: 738, expiration: "2026-07-27", volume: 82113, openInterest: 2452, volumeOpenInterest: 33.49, premium: 19460781, impliedVolatility: 10.6 },
        { symbol: "^SPX", contract: "SPXW260727P07450000", side: "Put", strike: 7450, expiration: "2026-07-27", volume: 3911, openInterest: 2849, volumeOpenInterest: 1.37, premium: 18831465, impliedVolatility: 9.5 },
        { symbol: "SPY", contract: "SPY260727P00742000", side: "Put", strike: 742, expiration: "2026-07-27", volume: 41380, openInterest: 1340, volumeOpenInterest: 30.88, premium: 18331340, impliedVolatility: 9.9 },
        { symbol: "SPY", contract: "SPY260727C00739000", side: "Call", strike: 739, expiration: "2026-07-27", volume: 63309, openInterest: 4331, volumeOpenInterest: 14.62, premium: 15542360, impliedVolatility: 9.3 },
        { symbol: "SPY", contract: "SPY260727C00740000", side: "Call", strike: 740, expiration: "2026-07-27", volume: 80349, openInterest: 5575, volumeOpenInterest: 14.41, premium: 15507357, impliedVolatility: 9.1 },
        { symbol: "SPY", contract: "SPY260727P00741000", side: "Put", strike: 741, expiration: "2026-07-27", volume: 36797, openInterest: 3610, volumeOpenInterest: 10.19, premium: 14019657, impliedVolatility: 10 },
        { symbol: "QQQ", contract: "QQQ260727P00680000", side: "Put", strike: 680, expiration: "2026-07-27", volume: 50750, openInterest: 6791, volumeOpenInterest: 7.47, premium: 13854750, impliedVolatility: 18.5 },
      ],
      methodology: "Historical fallback snapshot captured from delayed Yahoo Finance SPX, SPY and QQQ option chains at Friday close on July 24, 2026. The included contracts expired July 27 and the levels do not represent Friday intraday positioning. The serverless screener and primary option-chain provider returned no current gainers, losers or option rows when rechecked at 9:02 AM ET Friday, July 31. No usable fresh chain containing open interest, volume and implied volatility was available, so a new gamma, put/call or unusual-flow model was not published. The retained gamma estimate uses Black-Scholes gamma, reported implied volatility and open interest. Calls are treated as positive dealer gamma and puts as negative; exposure is estimated for a 1% underlying move. Walls are the highest-open-interest strikes within 5% of spot. This is an analytical estimate, not exchange-reported positioning or executable market data.",
    },
  },
};
